// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project.WebApi.Entities.Data;

#nullable disable

namespace Project.WebApi.Entities.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250417114229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DBDEV")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("ISEQ$$_73100");

            modelBuilder.HasSequence("ISEQ$$_73466");

            modelBuilder.HasSequence("ISEQ$$_73470");

            modelBuilder.HasSequence("ISEQ$$_73473");

            modelBuilder.HasSequence("ISEQ$$_73476");

            modelBuilder.HasSequence("ISEQ$$_73479");

            modelBuilder.HasSequence("ISEQ$$_73483");

            modelBuilder.HasSequence("ISEQ$$_73488");

            modelBuilder.HasSequence("ISEQ$$_73491");

            modelBuilder.HasSequence("ISEQ$$_73495");

            modelBuilder.HasSequence("ISEQ$$_73498");

            modelBuilder.HasSequence("ISEQ$$_73501");

            modelBuilder.HasSequence("ISEQ$$_73504");

            modelBuilder.HasSequence("ISEQ$$_73508");

            modelBuilder.HasSequence("ISEQ$$_73513");

            modelBuilder.HasSequence("ISEQ$$_73516");

            modelBuilder.HasSequence("ISEQ$$_73520");

            modelBuilder.HasSequence("ISEQ$$_73523");

            modelBuilder.HasSequence("ISEQ$$_73526");

            modelBuilder.HasSequence("ISEQ$$_73529");

            modelBuilder.HasSequence("ISEQ$$_73533");

            modelBuilder.HasSequence("ISEQ$$_73543");

            modelBuilder.HasSequence("ISEQ$$_73546");

            modelBuilder.HasSequence("ISEQ$$_73550");

            modelBuilder.HasSequence("ISEQ$$_73553");

            modelBuilder.HasSequence("ISEQ$$_73556");

            modelBuilder.HasSequence("ISEQ$$_73559");

            modelBuilder.HasSequence("ISEQ$$_73563");

            modelBuilder.HasSequence("ISEQ$$_73566");

            modelBuilder.Entity("Project.WebApi.Entities.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("DATE");

                    b.Property<int?>("ChangedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("RecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("SYS_C008258");

                    b.ToTable("Audit", "DBDEV");
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuditId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("SYS_C008260");

                    b.HasIndex("AuditId");

                    b.ToTable("AuditEntry", "DBDEV");
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers", "DBDEV");
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Created_At");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Created_By");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Deleted_At");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Deleted_By");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Icon")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Is_Active")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Is_Deleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentNavigationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Parent_Navigation_Id");

                    b.Property<string>("Route")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValueSql("'#'");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Updated_At");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Updated_By");

                    b.HasKey("Id")
                        .HasName("SYS_C007592");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ParentNavigationId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "Code" }, "SYS_C007593")
                        .IsUnique();

                    b.ToTable("Menus", "DBDEV");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CUSTOMER",
                            Description = "Customer Management",
                            Name = "Customer",
                            Order = 1,
                            Route = "/customer"
                        });
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Created_At");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Created_By");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Deleted_At");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Deleted_By");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Is_Active")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Is_Deleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Updated_At");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Updated_By");

                    b.HasKey("Id")
                        .HasName("SYS_C007603");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Roles", "DBDEV");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrator Role",
                            IsActive = 1,
                            Name = "Admin",
                            Order = 1
                        });
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.RoleGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Create")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("Delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("Read")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Role_Id");

                    b.Property<int?>("Update")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id")
                        .HasName("SYS_C007597");

                    b.HasIndex("RoleId");

                    b.ToTable("Role_Grant", "DBDEV");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Create = 1,
                            Delete = 1,
                            Read = 1,
                            RoleId = 1,
                            Update = 1
                        });
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.RoleMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Created_At");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Created_By");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Deleted_At");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Deleted_By");

                    b.Property<int?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Is_Active")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Is_Deleted")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("MenuId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Menu_Id");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Role_Id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Updated_At");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Updated_By");

                    b.HasKey("Id")
                        .HasName("SYS_C007599");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Role_Menu", "DBDEV");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = 1,
                            MenuId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Created_At");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Created_By");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Deleted_At");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Deleted_By");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Is_Active")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Is_Deleted")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("LastAccess")
                        .HasColumnType("DATE")
                        .HasColumnName("Last_Access");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Updated_At");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpdatedByNavigationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("SYS_C007617");

                    b.HasIndex("UpdatedByNavigationId");

                    b.ToTable("Users", "DBDEV");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Email = "anton@gmail.com",
                            Fullname = "Anton",
                            IsActive = 1,
                            IsDeleted = 0,
                            LastAccess = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "zImqzO3cO0GZPANlb96bk18UgYq9tB4+hNA+N/QoyzI=",
                            Username = "Anton"
                        });
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Created_At");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Created_By");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Deleted_At");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Deleted_By");

                    b.Property<int?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Is_Active")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Is_Deleted")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Role_Id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Updated_At");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Updated_By");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("User_Id");

                    b.HasKey("Id")
                        .HasName("SYS_C007605");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("RoleId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UserId");

                    b.ToTable("User_Role", "DBDEV");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = 1,
                            RoleId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Created_At");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("DATE")
                        .HasColumnName("Expired_At");

                    b.Property<string>("Ip")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("IP");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Refresh_Token");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("User_Agent");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("User_Id");

                    b.HasKey("Id")
                        .HasName("SYS_C007610");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "RefreshToken" }, "SYS_C007611")
                        .IsUnique();

                    b.ToTable("User_Token", "DBDEV");
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.AuditEntry", b =>
                {
                    b.HasOne("Project.WebApi.Entities.Models.Audit", "Audit")
                        .WithMany("AuditEntries")
                        .HasForeignKey("AuditId")
                        .HasConstraintName("fk_Audit");

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.Menu", b =>
                {
                    b.HasOne("Project.WebApi.Entities.Models.User", "CreatedByNavigation")
                        .WithMany("MenuCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("SYS_C007635");

                    b.HasOne("Project.WebApi.Entities.Models.User", "DeletedByNavigation")
                        .WithMany("MenuDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("SYS_C007637");

                    b.HasOne("Project.WebApi.Entities.Models.Menu", "ParentNavigation")
                        .WithMany("InverseParentNavigation")
                        .HasForeignKey("ParentNavigationId")
                        .HasConstraintName("SYS_C007594");

                    b.HasOne("Project.WebApi.Entities.Models.User", "UpdatedByNavigation")
                        .WithMany("MenuUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("SYS_C007636");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ParentNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.Role", b =>
                {
                    b.HasOne("Project.WebApi.Entities.Models.User", "CreatedByNavigation")
                        .WithMany("RoleCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("SYS_C007646");

                    b.HasOne("Project.WebApi.Entities.Models.User", "DeletedByNavigation")
                        .WithMany("RoleDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("SYS_C007648");

                    b.HasOne("Project.WebApi.Entities.Models.User", "UpdatedByNavigation")
                        .WithMany("RoleUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("SYS_C007647");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.RoleGrant", b =>
                {
                    b.HasOne("Project.WebApi.Entities.Models.Role", "Role")
                        .WithMany("RoleGrants")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("SYS_C007641");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.RoleMenu", b =>
                {
                    b.HasOne("Project.WebApi.Entities.Models.User", "CreatedByNavigation")
                        .WithMany("RoleMenuCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("SYS_C007643");

                    b.HasOne("Project.WebApi.Entities.Models.User", "DeletedByNavigation")
                        .WithMany("RoleMenuDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("SYS_C007645");

                    b.HasOne("Project.WebApi.Entities.Models.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .HasConstraintName("SYS_C007600");

                    b.HasOne("Project.WebApi.Entities.Models.Role", "Role")
                        .WithMany("RoleMenus")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("SYS_C007642");

                    b.HasOne("Project.WebApi.Entities.Models.User", "UpdatedByNavigation")
                        .WithMany("RoleMenuUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("SYS_C007644");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("Menu");

                    b.Navigation("Role");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.User", b =>
                {
                    b.HasOne("Project.WebApi.Entities.Models.User", "UpdatedByNavigation")
                        .WithMany()
                        .HasForeignKey("UpdatedByNavigationId");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.UserRole", b =>
                {
                    b.HasOne("Project.WebApi.Entities.Models.User", "CreatedByNavigation")
                        .WithMany("UserRoleCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("SYS_C007650");

                    b.HasOne("Project.WebApi.Entities.Models.User", "DeletedByNavigation")
                        .WithMany("UserRoleDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("SYS_C007652");

                    b.HasOne("Project.WebApi.Entities.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("SYS_C007606");

                    b.HasOne("Project.WebApi.Entities.Models.User", "UpdatedByNavigation")
                        .WithMany("UserRoleUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("SYS_C007651");

                    b.HasOne("Project.WebApi.Entities.Models.User", "User")
                        .WithMany("UserRoleUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("SYS_C007649");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("Role");

                    b.Navigation("UpdatedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.UserToken", b =>
                {
                    b.HasOne("Project.WebApi.Entities.Models.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("SYS_C007653");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.Audit", b =>
                {
                    b.Navigation("AuditEntries");
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.Menu", b =>
                {
                    b.Navigation("InverseParentNavigation");

                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.Role", b =>
                {
                    b.Navigation("RoleGrants");

                    b.Navigation("RoleMenus");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.WebApi.Entities.Models.User", b =>
                {
                    b.Navigation("MenuCreatedByNavigations");

                    b.Navigation("MenuDeletedByNavigations");

                    b.Navigation("MenuUpdatedByNavigations");

                    b.Navigation("RoleCreatedByNavigations");

                    b.Navigation("RoleDeletedByNavigations");

                    b.Navigation("RoleMenuCreatedByNavigations");

                    b.Navigation("RoleMenuDeletedByNavigations");

                    b.Navigation("RoleMenuUpdatedByNavigations");

                    b.Navigation("RoleUpdatedByNavigations");

                    b.Navigation("UserRoleCreatedByNavigations");

                    b.Navigation("UserRoleDeletedByNavigations");

                    b.Navigation("UserRoleUpdatedByNavigations");

                    b.Navigation("UserRoleUsers");

                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
